community_scripts.json, scripts/Win_Printers_List_Installed.ps1, scripts/Win_Windows_Update_Block_Win11.ps1
added in script to list all installed printers and block windows 11 upgrades
=> Dinger1986 patch 1

scripts_wip/itNGO - Disable Windows Feeds.ps1, scripts_wip/itNGO - Disallow WinRM Client Digest authentication.ps1, scripts_wip/itNGO - Disallow WinRM from storing RunAs credentials.ps1, scripts_wip/itNGO - Encryption Oracle-Defense.ps1, scripts_wip/itNGO - InstallWindowsUpdatesOnTrigger.ps1, scripts_wip/itNGO - MSOffice Disable SaveToOneDrive.bat, scripts_wip/itNGO - Network access_ Do not allow anonymous enumeration of SAM accounts and shares.ps1, scripts_wip/itNGO - PreviewBuildsBlock.ps1, scripts_wip/itNGO - Printers - Security Check KB5005010.ps1, scripts_wip/itNGO - Remote host allows delegation of non-exportable credentials.ps1, scripts_wip/itNGO - Security Bulletin MS15-077 - Disable ATMFD.ps1, scripts_wip/itNGO - Turn off Autoplay.ps1, scripts_wip/itNGO - Turn on certificate address mismatch warning.ps1, scripts_wip/itNGO - Windows 10_11_2016_2019_2022 disable Telemetry.ps1, scripts_wip/itNGO - Windows Activation check.ps1, scripts_wip/itNGO - Windows Components_Event Log Service.ps1, scripts_wip/itNGO - Windows Disable Fast Start.ps1
Instead using GPOs want to make it possible to do all with RTMM....
=> Some Scripts we are Using as GPO-Replacement

scripts/Win_Powershell_TestPATH.bat
Shows the registry type of the $PATH environmental variable.
=> Check registry type for PATH

scripts_wip/Win_Disk_Space_Check.ps1
Tested in latest version of TacticalRMM.
=> Added script for checking disk space

scripts/Win_Sophos_EndpointProtection_Install.ps1
Fails on systems that are defaulting to TLS 1.1. Sophos api endpoint requires TLS 1.2.
=> Updated to set TLS version

scripts_wip/Win_PerchLogShipper_Install.ps1
=> Added uninstall option

scripts_wip/Win_Eset_Check_AV_Status.ps1
The script is to long to paste it in discord. :-)
To use ermm.exe for monitoring, it needs some configuration to whitelist powershell (https://help.eset.com/eea/7/en-US/how_activate_rmm.html)
=> added script to monitor Eset security products with ermm.exe

scripts_staging/Win_Hello_World.ps1
I didn't see where the `json` file applied to `scripts_staging` so I didn't add it.
=> Sample Hello World script for PowerShell

scripts_wip/linux_disk_usage.sh
Just gives a little bit more info
=> Specify filesystem and usage in linux disk usage check

scripts_wip/Win_CyberCNS_Install.ps1
Fixes for updated CyberCNS portal.
=> Cyber cns updates

community_scripts.json, scripts/Win_WinGet_Manage_Apps.ps1
Add Winget app management script using chocolately manage apps script as a base
=> Add Winget

community_scripts.json, scripts/Win_TRMM_Mesh_Install.ps1
Install MeshCentral from Tactical if the Mesh install failed.
=> Install MeshCentral from Tactical

scripts_staging/Win_Drive_Info_Get.ps1
fixes missing } and fix SystemDrive check
=> fix Win_Drive_Info_Get.ps1 script

scripts_wip/Win_Windows_Backup_check
the script has already been tested. It can certainly be improved but is in good condition for the beginning.
=> Script for windows backup check

community_scripts.json, scripts/Win_ESET_ProtectAgent_Install.ps1
With this will be installed ESET Protect Agent so that the Computer will be seen in ESET Protect Console to distribute the endpoint security.
=> ESET Protect Agent Installation

scripts_wip/trmm-module-manager.py
First version of the TRMM Python module manager.
=> trmm-module-manager.py: first version

community_scripts.json, scripts/Win_ESET_ThreatScan.ps1
This PR adds a script to scan using ESET Endpoint Antivirus (also should work with ESET Endpoint Security, etc).
See https://help.eset.com/efsw/10/en-US/idh_config_ermm.html for more info
=> Add ESET scanning script

scripts_wip/all_pc_online_check.py
This script will ping a host to determine if the PC is online. If a ping is successful, a failure result is returned so it can be used in alerts.
=> PC online check to send an alert when a PC comes online

scripts_wip/Win_DuoAuthLogon_Manage.ps1
Tested on Windows 10 Professional.
=> Updated to use faster registry search

scripts_wip/Win_IE_Remove.ps1
Added acl settings for stubborn files
added force reboot example
=> Created script to remove IE11

scripts_wip/Win_Software_McAfee_check.ps1, scripts_wip/Win_Software_McAfee_task_uninstall.ps1
This uninstall script works but needs documenting, and maybe more testing. The corresponding "check" script is included.
=> Add: McAfee uninstall and check scripts

scripts_wip/Win_RemoteDesktopApp.ps1
=> Install Remote App for Azure Virtual Desktop

scripts_wip/Win_Winget_InstallIfMissing.ps1
=> WIP Adding winget install script

scripts_staging/Win_StorageCraftImageManager_Status.ps1
Found and corrected another instance where I was using C:\Windows\Temp instead of the Temp folder inside the TRMM Agent.
Added additional error handling around making a copy of the ImageManager.mdb.
=> Update - SPX ImageManager Status

scripts_wip/Win_CyberCNS_Install.ps1
updated to not need executable
=> Updated for CyberCNS v4

community_scripts.json, scripts/Win_Chocolatey_List_Installed.bat, scripts/Win_Chocolatey_Manage_Apps_Bulk.ps1, scripts_wip/Win_SMB1_CheckIfEnabled.ps1, scripts_wip/Win_Security_Vuln_scanner.ps1
Batch 1 of choco scripts changed to static paths
If it looks good, I'll see what others need to be updated
=> Refactor choco and add static choco paths

scripts_wip/Win_PrinterInstaller.ps1
added fixes for multiple printers
=> created printer installer script

scripts_wip/Win_DuoAuthLogon_Manage.ps1
Changed the script to just install the latest version instead of remove old and install new.
=> changed upgrade to not uninstall first

community_scripts.json, scripts/Win_ScreenConnectAIO.ps1
json missing syntax, and wrong default parameters. Linting script too.
=> Fixing Screenconnect AIO

scripts/Win_IIS_Check_SSL_Certs.ps1
Add check for friendly name, use Subject if not present
=> Fix variable name certfileMY

community_scripts.schema.json
Just add the env and run_as_user keys to the schema.
=> Proposed work for amidaware/community-scripts#245

scripts/Win_Chocolatey_Manage_Apps_Bulk.ps1, scripts_staging/Win_Defender_Enable_Exclusions.ps1, scripts_wip/Win_Dell_RAIDmonitor.ps1
For choco bulk someone please test.
One concern: Not sure when that feature was added to choco but if choco is old version and doesn't have feature what happens?
=> Choco bulk: Add list-upgradeable. Add Defender enable exclusions starter list

scripts/Win_Teamviewer_Get_ID.ps1
either change the = to += or the second foreach is redundant as the goodpath is just the last path wich worked.
=> Changed the Teamviewer Script to include all path keys and not just the last one wich worked.
